TodoApp/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TodoApp.Application.Interfaces;
using TodoApp.Application.ViewModels;
using TodoApp.Domain.Enums;

namespace TodoApp.Controllers
{

    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        private readonly ITaskService _taskService;
        public DashboardController(ITaskService taskService)
        {
            _taskService = taskService;
        }


        public async Task<IActionResult> Index()
        {
            var usersTasks = (await _taskService.GetAllUsersTasks()).GroupBy(task => task.UserId);

            if(usersTasks.Any() )
                return View(new DashboardViewModel
                {
                    Tasks = usersTasks.Select(tasks => new TasksViewModel
                    {
                        Tasks = tasks,
                        HomeCount = tasks.Count(task => task.Category == ETaskCategory.Home),
                        PersonalCount = tasks.Count(task => task.Category == ETaskCategory.Personal),
                        ShoppingCount = tasks.Count(task => task.Category == ETaskCategory.Shopping),
                        WorkCount = tasks.Count(task => task.Category == ETaskCategory.Work),
                        TasksCount = tasks.Count(),
                    }).ToList()
                });

            return View();
        }
    }
}

TodoApp/Controllers/TaskController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TodoApp.Application.DTOs;
using TodoApp.Application.Interfaces;
using TodoApp.Application.ViewModels;
using TodoApp.Domain.Enums;

namespace TodoApp.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private readonly ITaskService _taskService;
        public TaskController(ITaskService taskService)
        {
            _taskService = taskService;
        }

        public async Task<ActionResult> Index()
        {
            var tasks = await _taskService.GetAllTasks();

            #region Sorting tasks
            // For some reason, query maker is not allowing sort by incomplete tasks after date sorting
            var incompleteTasks = tasks.Where(t => !t.IsCompleted)
                               .OrderBy(t => t.Deadline)
                               .ToList();

            var completedTasks = tasks.Where(t => t.IsCompleted)
                                      .OrderBy(t => t.Deadline)
                                      .ToList();

            var sortedTasks = incompleteTasks.Concat(completedTasks);
            #endregion

            return View(new TasksViewModel
            {
                Tasks = sortedTasks,
                HomeCount = tasks.Count(task => task.Category == ETaskCategory.Home),
                PersonalCount = tasks.Count(task => task.Category == ETaskCategory.Personal),
                ShoppingCount = tasks.Count(task => task.Category == ETaskCategory.Shopping),
                WorkCount = tasks.Count(task => task.Category == ETaskCategory.Work),
                TasksCount = tasks.Count(),
            });
        }

        public async Task<ActionResult> Details(int id)
        {
            var model = await _taskService.GetAsync(id);
            if(model == null)
                return RedirectToAction(nameof(Index));

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Domain.Entities.Task task)
        {
            try
            {
                ModelState.Remove("UserId"); // Ugly solution, create another VM should be greater than this
                ModelState.Remove("User"); // Ugly solution, create another VM should be greater than this
                if (!ModelState.IsValid)
                    return View(task);

                await _taskService.CreateTask(task);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            var model = await _taskService.GetAsync(id);

            if(model == null)
                return RedirectToAction(nameof(Index));

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(int id, Domain.Entities.Task task)
        {
            try
            {
                await _taskService.UpdateTask(task);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<ActionResult> MarkTaskAsCompleted(int id)
        {
            try
            {
                await _taskService.MarkTaskAsCompleted(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await _taskService.DeleteTask(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        [HttpPost]
        public async Task<ActionResult> SendTasksEmail(SendEmailDto input)
        {
            await _taskService.SendTasksEmail(input.Email);

            return Ok();
        }
    }
}

TodoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | TodoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TodoApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-check-circle-fill text-success"></i> TDApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User!.Identity!.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Tasks</a>
                            </li>

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                                </li>
                            }
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (User!.Identity!.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <i class="bi bi-person-gear"></i>
                                        }
                                        @User.Identity.Name
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Account</a></li>
                                        <li><a class="dropdown-item" href="#">Settings</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Login</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - Cloud++
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>